project:
  name: quickstart-swift-digital-connectivity
  owner: quickstart-eng@amazon.com
  package_lambda: false
  #  s3_regional_buckets: true
  regions:
  - us-west-2
  - ap-south-1
  - eu-west-1
  - us-east-1
  - ca-central-1
  - ap-northeast-1
  - ap-southeast-1
  - us-east-2
  - eu-west-2
  - eu-central-1
  - us-west-1
  - eu-west-3
tests:
  example_test:
    template: index.html
